server:
  error:
    include-message: always
    include-exception: 'true'
    include-stacktrace: always
marketpeace:
  app:
    jwtSecret: "marketpeacesecret"
    jwtExpirationMs: 86400000
spring:
  security:
    user:
      name: "admin"
      password: "admin"
  datasource:
    url: 'jdbc:mysql://localhost:3306/marketpeacedb'
    username: admin
    password: Admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  web:
    resources:
      add-mappings: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
